### ISSUE TITLE
Only the first cell is visible with certain files

### ISSUE THREAD

**Issue by improbable-22** [kokes/nbviewer.js#28] opened 2018-06-01 08:23 UTC
When viewing a notebook generated by [Literate.jl](https://github.com/fredrikekre/Literate.jl), only the first cell is displayed. Opening their [example notebook](https://nbviewer.jupyter.org/github/fredrikekre/Literate.jl/blob/gh-pages/v0.2.1/generated/example.ipynb) using the [online preview](https://kokes.github.io/nbviewer.js/viewer.html) shows the problem. 

This is the same issue as [nbviewer-app issue 6](https://github.com/tuxu/nbviewer-app/issues/6), where @tuxu tells me that in "the first output cell, [] nbviewer.js expects an array, but only a string literal is found".

**Comment by kokes** [comment] 2018-06-01 19:56
Well spotted, I didn't realise the text could be a plain string. I pushed a fix ([e1266d](https://github.com/kokes/nbviewer.js/commit/e1266dfb78b7a8a06372b9c4cbc354b9f0cceaa7)) I've also noticed that this may affect code input as well (meaning that could be a simple string, not a list), so I fixed that as well (see [647a9a](https://github.com/kokes/nbviewer.js/commit/647a9a662d1925857c713bc2c35a3f21d9961d91)). Can you double check it works as expected now?

**Comment by improbable-22** [comment] 2018-06-01 21:33
Many thanks, that was quick! The example file linked above now works perfectly. 

However when I try other notebooks which contain graphs, these are not displayed. Again only the ones generated by Literate.jl, not the ones saved directly by Jupyter. The graphs are displayed when opened locally. I wonder if this is a related issue? 

However I don't have any nice short examples to hand, to share. And I seem to have broken everything locally today, and it's late. I'll try to attach one... on monday. 

For now I attach a `.jl` file [test-fig.jl.txt](https://github.com/kokes/nbviewer.js/files/2064192/test-fig.jl.txt) which I believe should have this issue, once you do this: 
```julia
julia> using Literate
julia> Literate.notebook("/Users/me/Desktop/test-fig.jl", "/Users/me/Desktop/")
```

**Comment by improbable-22** [comment] 2018-06-01 21:54
OK here's a test file, much like the above: [test-fig.ipynb.zip](https://github.com/kokes/nbviewer.js/files/2064243/test-fig.ipynb.zip)

But rather than not showing the plot (as happened with some other files I can't share) this one shows it three times, the first one gigantic. In pictures: 

![screen shot 2018-06-01 at 11 49 38 pm](https://user-images.githubusercontent.com/29553230/40865005-83cfdfae-65f6-11e8-8e6b-81ac8e80c33d.JPG)
![screen shot 2018-06-01 at 11 49 49 pm](https://user-images.githubusercontent.com/29553230/40865006-83ed9e7c-65f6-11e8-8e5a-a0a3aff3c92d.JPG)

As before, I've no idea where the blame lies here. But the same notebook does open correctly in [nteract](https://github.com/nteract/nteract), and show the plot correctly.

**Comment by kokes** [comment] 2018-06-01 22:05
I only skimmed the JSON, but my guess is: there are three formats supplied: SVG, PNG and one other (as fallbacks, I guess). And instead of choosing one, I’m rendering all three. 

In general, I render all outputs I get, mostly because oftentimes it’s an image and some text above it. Not sure what the specs say in this case. Will look into it on Monday.

**Comment by kokes** [comment] 2019-02-09 08:58
Well, the first figure is no longer huge (https://github.com/kokes/nbviewer.js/commit/6c353e8a4af36438e35900a363312ade8f41fe5c), but there are still three of them. I haven't looked into the specs, but I don't feel comfortable choosing only some output to be rendered - as I said above, sometimes you want multiple objects rendered.

**Comment by improbable-22** [comment] 2019-02-09 11:09
Thanks for circling back to this. I've just made an issue on Literate.jl as linked.

**Comment by improbable-22** [comment] 2019-02-09 18:02
Digging a little bit, maybe this is the right spec: 

https://nbformat.readthedocs.io/en/latest/format_description.html#display-data 

It's not entirely spelled out there whether (say) "text/plain" and "image/png" are alternatives , or additions. Is this obvious? Certainly that seems to be what Literate is producing: 
```
  {
   "outputs": [
    {
     "output_type": "execute_result",
     "data": {
      "text/plain": "Plot{Plots.GRBackend() n=1}",
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAlgAAAGQCAIAAAD9V4nPAAAABmJLR0QA/wD/AP+gvaeTAAAgAElEQVR4nO3daXwc1Zko/OdUdaulXtTaZUtqtSxblmzMYmyZs <snip!!> ",
      "text/html": [
       "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n",
       "<svg xmlns=\"http://www.w3.org/2000/svg\" xmlns:xlink=\"http://www.w3.org/1999/xlink\" width=\"600\" height=\"400\" viewBox=\"0 0 2400 1600\">\n",
       "<defs>\n",
...
       "</svg>\n"
      ]
     },
     "metadata": {},
     "execution_count": 2
    }
   ],
   "cell_type": "code",
   "source": [
    "using Plots\n",
    "plot(rand(20))"
   ],
   "metadata": {},
   "execution_count": 2
  },
```
The "text/plain" option is never displayed. 

Opening the file in Jupyter, the graph output is not visible at all. But running it again produces this, with just one format: 
```
{
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "image/svg+xml": [
       "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n",
       "<svg xmlns=\"http://www.w3.org/2000/svg\" 
...
       "</svg>\n"
      ]
     },
     "execution_count": 2,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "using Plots\n",
    "plot(rand(20))"
   ]
  },
```
If I explicitly make a cell which outputs two graphs (in Jupyter) then it looks like this -- each gets its own explicit `"data": {` :
```
{
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "image/svg+xml": [
       "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n",
       "<svg xmlns=\"http://www.w3.org/2000/svg\" xmlns:xlink=\"http://www.w3.org/1999/xlink\" width=\"600\" height=\"400\" 
...
       "<circle clip-path=\"url(#clip6603)\" style=\"fill:#000000; stroke:none; fill-opacity:1\" cx=\"222.522\" cy=\"1133.97\" r=\"18\"/>\n",
       "<circle clip-path=\"url(#clip6603)\" style=\"fill:#009af9; stroke:none; fill-opacity:1\" cx=\"222.522\" cy=\"1133.97\" r=\"14\"/>\n",
       "<circle clip-path=\"url(#clip6603)\" style=\"fill:#000000; stroke:none; fill-opacity:1\" cx=\"448.923\" cy=\"552.32\" r=\"18\"/>\n",
...
       "</svg>\n"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "image/svg+xml": [
       "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n",
       "<svg xmlns=\"http://www.w3.org/2000/svg\" xmlns:xlink=\"http://www.w3.org/1999/xlink\" width=\"600\" height=\"400\" viewBox=\"0 0 2400 1600\">\n",
       "<defs>\n",
       "  <clipPath id=\"clip6800\">\n",
       "    <rect x=\"0\" y=\"0\" width=\"2000\" height=\"2000\"/>\n",
       "  </clipPath>\n",
...

       "</svg>\n"
      ]
     },
     "execution_count": 5,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "using Plots\n",
    "display(scatter(rand(10)))\n",
    "plot(rand(5))"
   ]
  },
```
I attach all of these files, just in case: [four-files-issue-28.zip](https://github.com/kokes/nbviewer.js/files/2848096/four-files-issue-28.zip)

**Comment by kokes** [comment] 2019-02-09 19:17
You're right - this whole thing stems from my memory that images (used to, I guess) have an imaged displayed alongside a text description (usually just dimensions). That was either in v3 or I just have a foggy memory.

In any case, I tried to reproduce it by plotting a basic matplotlib and just the image is shown in Jupyter. Just like in your example above.

So I guess the task now is to select the one canonical display type (or what sort of ordering to follow here) - do you have an idea of what that might be? When I was fixing a different thing, I noticed that I'm doing that already in `text/plain` vs. `text/html`, where the former is a fallback for the latter, see https://github.com/kokes/nbviewer.js/blob/master/lib/nbv.js#L193.

**Comment by improbable-22** [comment] 2019-02-09 20:29
I'd guess SVG should come before PNG, just so that I can zoom in, but I don't know if there's a canonical order somewhere. I'll ask in the other thread.

**Comment by kokes** [comment] 2019-02-10 15:56
@improbable22 This looks like it, doesn't it? https://github.com/jupyter/nbconvert/blob/master/nbconvert/utils/base.py#L16

Though I'd also check that at least one of these mime types is present.

Oh and I don't think I've ever seen `text/markdown` in `display_data` - no that I wouldn't know how to handle it, I'll just have to check it out.

**Comment by kokes** [comment] 2019-02-10 16:08
I've morphed this into a slightly more clearly defined issue where I'd like to resolve a few other issues as well, since it's not unlikely to break a few things.

**Closed as completed** 2019-02-10 17:02 UTC

**Comment by kokes** [comment] 2019-02-10 17:03
So it's fixed now, I'm letting the other issue open as there area few unresolved subissues.

**Comment by improbable-22** [comment] 2019-02-11 13:15
Great, many thanks for the fix. And sorry about the rambling issue, a more focused one makes sense.
